import { randomUUID } from 'crypto'
import { NextResponse, type NextRequest } from 'next/server'
import { z } from 'zod'
import { requireAdmin } from '@/lib/auth/requireAdmin'
import { supabaseAdmin } from '@/lib/supabase/server'
import {
  MAX_UPSELL_IMAGE_BYTES,
  uploadedImageMimeTypes,
  uploadedUpsellImageMutationSchema,
} from '@/lib/upsells/media'

const upsellIdSchema = z.string().uuid('Identifiant upsell invalide')

async function getUploadedImage(admin: ReturnType<typeof supabaseAdmin>, upsellId: string, imageId: string) {
  const { data, error } = await admin
    .from('upsell_images')
    .select('id, upsell_id, source, storage_path, alt_text')
    .eq('id', imageId)
    .eq('upsell_id', upsellId)
    .maybeSingle()

  if (error) throw error
  if (!data) return null
  if (data.source !== 'upload' || !data.storage_path) return null
  // Storage paths are generated by this API. Keep the ownership boundary
  // explicit even when the database row is accidentally malformed.
  if (!data.storage_path.startsWith(`upsells/${upsellId}/`)) return null
  return data
}

function parseImageFile(value: FormDataEntryValue | null) {
  if (!(value instanceof File)) return { error: 'Fichier image requis' as const }
  const extension = uploadedImageMimeTypes[value.type as keyof typeof uploadedImageMimeTypes]
  if (!extension || value.size === 0 || value.size > MAX_UPSELL_IMAGE_BYTES) {
    return { error: 'Image JPEG, PNG, WebP ou AVIF de 10 Mo maximum requise' as const }
  }
  return { file: value, extension }
}

export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAdmin(request)
  if (!auth.ok) return auth.response

  const { id } = await params
  const parsedUpsellId = upsellIdSchema.safeParse(id)
  if (!parsedUpsellId.success) return NextResponse.json({ error: parsedUpsellId.error.issues[0]?.message }, { status: 400 })
  const form = await request.formData()
  const parsedFile = parseImageFile(form.get('file'))
  if ('error' in parsedFile) return NextResponse.json({ error: parsedFile.error }, { status: 400 })
  const { file, extension } = parsedFile

  const admin = supabaseAdmin()
  const { data: upsell, error: upsellError } = await admin.from('upsells').select('id').eq('id', parsedUpsellId.data).maybeSingle()
  if (upsellError || !upsell) return NextResponse.json({ error: 'Upsell introuvable' }, { status: 404 })

  const path = `upsells/${parsedUpsellId.data}/${randomUUID()}.${extension}`
  const { error: uploadError } = await admin.storage.from('upsell-images').upload(path, Buffer.from(await file.arrayBuffer()), {
    contentType: file.type,
    cacheControl: '31536000',
    upsert: false,
  })
  if (uploadError) return NextResponse.json({ error: 'Échec du téléversement' }, { status: 500 })

  const { data: lastImage } = await admin.from('upsell_images').select('position').eq('upsell_id', parsedUpsellId.data).order('position', { ascending: false }).limit(1).maybeSingle()
  const { data: image, error: insertError } = await admin.from('upsell_images').insert({
    upsell_id: parsedUpsellId.data,
    source: 'upload',
    storage_path: path,
    position: (lastImage?.position ?? -1) + 1,
  }).select().single()
  if (insertError) {
    await admin.storage.from('upsell-images').remove([path])
    return NextResponse.json({ error: 'Échec de l’enregistrement de l’image' }, { status: 500 })
  }
  return NextResponse.json({ image }, { status: 201 })
}

/** Replace an existing uploaded image while preserving its gallery position. */
export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAdmin(request)
  if (!auth.ok) return auth.response

  const { id } = await params
  const parsedUpsellId = upsellIdSchema.safeParse(id)
  if (!parsedUpsellId.success) return NextResponse.json({ error: parsedUpsellId.error.issues[0]?.message }, { status: 400 })
  const form = await request.formData()
  const mutation = uploadedUpsellImageMutationSchema.safeParse({ image_id: form.get('image_id') })
  if (!mutation.success) return NextResponse.json({ error: mutation.error.issues[0]?.message ?? 'Image invalide' }, { status: 400 })
  const parsedFile = parseImageFile(form.get('file'))
  if ('error' in parsedFile) return NextResponse.json({ error: parsedFile.error }, { status: 400 })

  const admin = supabaseAdmin()
  const image = await getUploadedImage(admin, parsedUpsellId.data, mutation.data.image_id)
  if (!image) return NextResponse.json({ error: 'Image uploadée introuvable' }, { status: 404 })

  const path = `upsells/${parsedUpsellId.data}/${randomUUID()}.${parsedFile.extension}`
  const { error: uploadError } = await admin.storage.from('upsell-images').upload(path, Buffer.from(await parsedFile.file.arrayBuffer()), {
    contentType: parsedFile.file.type,
    cacheControl: '31536000',
    upsert: false,
  })
  if (uploadError) return NextResponse.json({ error: 'Échec du téléversement' }, { status: 500 })

  const altText = form.get('alt_text')
  const update: { storage_path: string; alt_text?: string | null; updated_at: string } = {
    storage_path: path,
    updated_at: new Date().toISOString(),
  }
  if (typeof altText === 'string') update.alt_text = altText.trim().slice(0, 500) || null
  const { data: updated, error: updateError } = await admin
    .from('upsell_images')
    .update(update)
    .eq('id', image.id)
    .eq('upsell_id', parsedUpsellId.data)
    .select()
    .single()
  if (updateError) {
    await admin.storage.from('upsell-images').remove([path])
    return NextResponse.json({ error: 'Échec de l’enregistrement de l’image' }, { status: 500 })
  }

  const { error: cleanupError } = await admin.storage.from('upsell-images').remove([image.storage_path])
  if (cleanupError) {
    console.error('Échec du nettoyage de l’image remplacée:', cleanupError)
    return NextResponse.json({ image: updated, warning: 'Image remplacée, ancien fichier non nettoyé' }, { status: 200 })
  }
  return NextResponse.json({ image: updated })
}

/** Delete an uploaded image and its corresponding Storage object. */
export async function DELETE(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAdmin(request)
  if (!auth.ok) return auth.response

  const { id } = await params
  const parsedUpsellId = upsellIdSchema.safeParse(id)
  if (!parsedUpsellId.success) return NextResponse.json({ error: parsedUpsellId.error.issues[0]?.message }, { status: 400 })
  const parsedMutation = uploadedUpsellImageMutationSchema.safeParse({ image_id: new URL(request.url).searchParams.get('image_id') })
  if (!parsedMutation.success) return NextResponse.json({ error: parsedMutation.error.issues[0]?.message ?? 'Image invalide' }, { status: 400 })

  const admin = supabaseAdmin()
  const image = await getUploadedImage(admin, parsedUpsellId.data, parsedMutation.data.image_id)
  if (!image) return NextResponse.json({ error: 'Image uploadée introuvable' }, { status: 404 })

  const { error: deleteError } = await admin
    .from('upsell_images')
    .delete()
    .eq('id', image.id)
    .eq('upsell_id', parsedUpsellId.data)
  if (deleteError) return NextResponse.json({ error: 'Échec de la suppression de l’image' }, { status: 500 })

  const { error: cleanupError } = await admin.storage.from('upsell-images').remove([image.storage_path])
  if (cleanupError) {
    console.error('Échec du nettoyage Storage de l’image supprimée:', cleanupError)
    return NextResponse.json({ success: true, warning: 'Image supprimée, fichier Storage non nettoyé' })
  }
  return NextResponse.json({ success: true })
}
